/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.gruppe7.levelcommon.events;

import dk.gruppe7.common.annotations.Event;

/**
 *
 * @author movie
 */
@Event
public class LevelGenerationEvent {
    //Fires when a level has been generated by the LevelGenerator Component
}
